import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


const Home = () => {

  const content = [
    {title: "Documentation", text: "Find in-depth information about Next.js features and API.", link: "https://nextjs.org"},
    {title: "Learn", text: "Learn about Next.js in an interactive course with quizzes!", link: "https://nextjs.org/learn"},
    {title: "Examples", text: "Discover and deploy boilerplate example Next.js projects.", link: "https://github.com/vercel/next.js/tree/canary/examples"},
    {title: "Deploy", text: "Instantly deploy your Next.js site to a public URL with Vercel.", link: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"},
    ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container h-full my-0 mx-auto'>
        <h1 className='text-5xl font-bold text-center'>
          Welcome to <a className='text-blue-600' href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className='text-center  mt-3'>
          Get started by editing{' '}
          <code className='text-mono p-1 bg-gray-100 rounded'>pages/index.tsx</code>
        </p>

        <div className='grid grid-cols-2 gap-8 mt-8'>
          {content.map((item, index) => (
          <a className='p-8 rounded-2xl border-solid border border-gray-200 hover:bg-gray-100 group'
            href={item.link}
            target="_blank"
            key={index}
            rel="noopener noreferrer"
          >
            <h2 className='font-bold pb-3 text-2xl after:content-["→"] after:pl-2 group-hover:after:pl-5 after:duration-100 after:transition-all'>{item.title}</h2>
            <p className='text-lg'>
              {item.text}
            </p>
          </a>
          ))}
        </div>
      </main>

      <footer className='container flex'>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <Link href='/about' className='text-md'>About</Link>
      </footer>
    </div>
  )
}

export default Home